# Generated by Django 4.2.5 on 2023-12-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id_prodi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_prodi', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id_scrap', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_scrap', models.DateTimeField(auto_now_add=True)),
                ('teks', models.TextField(max_length=599999)),
                ('id_prodi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='getByQuery.prodi')),
            ],
        ),
    ]
